---
pipeline-vars: &pipeline-vars
  instanacd-github-api-token: ((instanacd-github-api-token))
  artifacts-instana-io: ((artifacts-instana-io))
  team-java-sign-key: ((team-java-sign-key))
  team-java-sign-password: ((team-java-sign-password))
  team-java-sonatype: ((team-java-sonatype))

gradle-params: &gradle-params
  PGP_KEY: ((team-java-sign-key))
  PGP_KEY_PASSWORD: ((team-java-sign-password))
  OSSRH_USERNAME: ((team-java-sonatype.username))
  OSSRH_PASSWORD: ((team-java-sonatype.password))

android-agent-git-repo-notagfilter: &android-agent-git-repo-notagfilter
  uri: https://github.ibm.com/instana/android-agent.git
  username: ((ibm-github-e-api-token))
  password: x-oauth-basic
  branch: ci_pipeline

android-agent-git-repo-releasetag: &android-agent-git-repo-releasetag
  <<: *android-agent-git-repo-notagfilter
  tag_filter: "release*"

android-agent-github-com-repo-master: &android-agent-github-com-repo-master
  uri: https://github.ibm.com/lsrlibj/android-agent.git
  username: ((ibm-github-e-api-token))
  password: x-oauth-basic
  branch: master

resources:
  - name: android-agent-source-notagfilter
    type: git
    icon: github
    source:
      <<: *android-agent-git-repo-notagfilter
  - name: android-agent-source-releasetag
    type: git
    icon: github
    source:
      <<: *android-agent-git-repo-releasetag
  - name: android-agent-github-com-source-master
    type: git
    icon: github
    source:
      <<: *android-agent-github-com-repo-master

jobs:
  - name: self-update
    plan:
      - get: android-agent-source-notagfilter
        trigger: true
      - set_pipeline: self
        file: android-agent-source-notagfilter/ci/pipeline.yml
        vars:
          branch: ci_pipeline
          ibm-github-e-api-token: ((ibm-github-e-api-token))

  - name: build-publish
    plan:
      - get: android-agent-source-releasetag
        trigger: true
      - task: build-publish
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gcr.io/k8s-brewery/instana/concourse-dind
              tag: mvn3-jdk8
              username: _json_key
              password: ((gcloud-agent-ci-account-key))
          inputs:
            - name: android-agent-source-releasetag
          params:
            <<: *gradle-params
          run:
            dir: android-agent-source-releasetag/
            path: bash
            args:
              - -cx
              - |
                export BUILD_PATH=$(pwd)
                echo "Building Android Agent"
                $BUILD_PATH/ci/build.sh

  - name: push-github-com
    plan:
      - get: android-agent-source-releasetag
        trigger: true
        passed: [ build-publish ]
        params: { fetch_tags: true }
      - put: android-agent-github-com-source-master
        params:
          repository: android-agent-source-releasetag
          merge: true
